// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {main} from '../models';

export function AddTask(arg1:string,arg2:string,arg3:string):Promise<number>;

export function DeleteTask(arg1:number):Promise<boolean>;

export function EditTask(arg1:number,arg2:string,arg3:string,arg4:time.Time):Promise<boolean>;

export function GetTasks():Promise<{[key: number]: main.Task}>;

export function Greet(arg1:string):Promise<string>;
