// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTask'](arg1, arg2, arg3);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function EditTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditTask'](arg1, arg2, arg3, arg4);
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
